name: CI Pipeline
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
  build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $DOCKER_TOKEN | docker login
            -u $DOCKER_USERNAME --password-stdin
      - run: docker build-t $USER/app:latest .
      - run: docker push $USER/app:latest
